version: "2"
checks:
    file-lines:
        config:
            threshold: 500
    method-lines:
        config:
            threshold: 100
exclude_patterns:
    - "src/IronHook.EntityFrameworkCore.PostgreSql/Migrations/",
    - "src/IronHook.EntityFrameworkCore.SqlServer/Migrations/",
    - "samples/IronHook.Web/Migrations/"
